update autotools chain
git-svn-id: https://svn.ic-s.nl/svn/dbmail/branches/dbmail_2_2_branch@2533 7b491191-dbf0-0310-aff6-d879d4d69008

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -867,6 +867,8 @@ USE_DM_GETOPT_TRUE
 USE_DM_GETOPT_FALSE
 WITHCHECK_TRUE
 WITHCHECK_FALSE
+MANPAGES_TRUE
+MANPAGES_FALSE
 MYSQL_TRUE
 MYSQL_FALSE
 PGSQL_TRUE
@@ -898,6 +900,7 @@ SQLITEINC
 DM_LOGDIR
 DM_CONFDIR
 DM_STATEDIR
+DM_PKGLIBDIR
 build
 build_cpu
 build_vendor
@@ -1520,6 +1523,7 @@ Optional Features:
 			  (and sometimes confusing) to the casual installer
   --enable-shared[=PKGS]  build shared libraries [default=no]
   --enable-static[=PKGS]  build static libraries [default=no]
+  --disable-manual        do not build or install manual pages
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-fast-install[=PKGS]
@@ -1530,6 +1534,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-logdir           use logdir for logfiles
+  --with-pkglibdir        use pkglibdir for dbmail libraries
   --with-mysql            use MySQL as database. Uses mysql_config
 	       		  for finding includes and libraries
   --with-pgsql            use PostgreSQL as database.
@@ -2597,17 +2602,29 @@ fi
   then
   	DM_LOGDIR="/var/log"
   else
-  	DM_LOGDIR="$logdirname"
+  	DM_LOGDIR=$logdirname
+  fi
+
+# Check whether --with-pkglibdir was given.
+if test "${with_pkglibdir+set}" = set; then
+  withval=$with_pkglibdir; pkglibdirname="$withval"
+fi
+
+  if test "x$pkglibdirname" = "x"
+  then
+  	DM_PKGLIBDIR="/usr/lib/dbmail"
+  else
+  	DM_PKGLIBDIR=$pkglibdirname
   fi
   if test "x$localstatedir" = 'x${prefix}/var'
   then
-  	DM_STATEDIR='/var/run'
+  	DM_STATEDIR="/var/run"
   else
   	DM_STATEDIR=$localstatedir
   fi
   if test "x$sysconfdir" = 'x${prefix}/etc'
   then
-  	DM_CONFDIR='/etc'
+  	DM_CONFDIR="/etc"
   else
   	DM_CONFDIR=$sysconfdir
   fi
@@ -2625,6 +2642,20 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
   fi
+{ echo "$as_me:$LINENO: checking whether to provide manual pages" >&5
+echo $ECHO_N "checking whether to provide manual pages... $ECHO_C" >&6; }
+# Check whether --enable-manual was given.
+if test "${enable_manual+set}" = set; then
+  enableval=$enable_manual;  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+  enable_manpages="no"
+else
+   { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  enable_manpages="yes"
+
+fi
+
 
 
 usemysql="no"
@@ -7062,6 +7093,16 @@ else
 fi
 
 
+
+if  test "$enable_manpages" = "yes" ; then
+  MANPAGES_TRUE=
+  MANPAGES_FALSE='#'
+else
+  MANPAGES_TRUE='#'
+  MANPAGES_FALSE=
+fi
+
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -8715,6 +8756,7 @@ fi
 
 
 
+
 # Check whether --enable-fast-install was given.
 if test "${enable_fast_install+set}" = set; then
   enableval=$enable_fast_install; p=${PACKAGE-default}
@@ -9300,7 +9342,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9303 "configure"' > conftest.$ac_ext
+  echo '#line 9345 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11553,11 +11595,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11556: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11598: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11560: \$? = $ac_status" >&5
+   echo "$as_me:11602: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11821,11 +11863,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11824: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11866: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11828: \$? = $ac_status" >&5
+   echo "$as_me:11870: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11925,11 +11967,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11928: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11970: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11932: \$? = $ac_status" >&5
+   echo "$as_me:11974: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14222,7 +14264,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14225 "configure"
+#line 14267 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14322,7 +14364,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14325 "configure"
+#line 14367 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16658,11 +16700,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16661: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16703: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16665: \$? = $ac_status" >&5
+   echo "$as_me:16707: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16762,11 +16804,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16765: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16807: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16769: \$? = $ac_status" >&5
+   echo "$as_me:16811: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18323,11 +18365,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18326: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18368: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18330: \$? = $ac_status" >&5
+   echo "$as_me:18372: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18427,11 +18469,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18430: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18472: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18434: \$? = $ac_status" >&5
+   echo "$as_me:18476: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20614,11 +20656,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20617: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20621: \$? = $ac_status" >&5
+   echo "$as_me:20663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20882,11 +20924,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20885: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20927: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20889: \$? = $ac_status" >&5
+   echo "$as_me:20931: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20986,11 +21028,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20989: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21031: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20993: \$? = $ac_status" >&5
+   echo "$as_me:21035: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23785,6 +23827,13 @@ echo "$as_me: error: conditional \"WITHCHECK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${MANPAGES_TRUE}" && test -z "${MANPAGES_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MANPAGES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MANPAGES\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -24509,6 +24558,8 @@ for ac_last_try in false false false false false :; do
 USE_DM_GETOPT_FALSE!$USE_DM_GETOPT_FALSE$ac_delim
 WITHCHECK_TRUE!$WITHCHECK_TRUE$ac_delim
 WITHCHECK_FALSE!$WITHCHECK_FALSE$ac_delim
+MANPAGES_TRUE!$MANPAGES_TRUE$ac_delim
+MANPAGES_FALSE!$MANPAGES_FALSE$ac_delim
 MYSQL_TRUE!$MYSQL_TRUE$ac_delim
 MYSQL_FALSE!$MYSQL_FALSE$ac_delim
 PGSQL_TRUE!$PGSQL_TRUE$ac_delim
@@ -24540,6 +24591,7 @@ SQLITEINC!$SQLITEINC$ac_delim
 DM_LOGDIR!$DM_LOGDIR$ac_delim
 DM_CONFDIR!$DM_CONFDIR$ac_delim
 DM_STATEDIR!$DM_STATEDIR$ac_delim
+DM_PKGLIBDIR!$DM_PKGLIBDIR$ac_delim
 build!$build$ac_delim
 build_cpu!$build_cpu$ac_delim
 build_vendor!$build_vendor$ac_delim
@@ -24567,7 +24619,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 59; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 62; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -25163,6 +25215,7 @@ fi
 DM_LOGDIR:     $DM_LOGDIR
 DM_CONFDIR:    $DM_CONFDIR
 DM_STATEDIR:   $DM_STATEDIR
+DM_PKGLIBDIR:  $DM_PKGLIBDIR
 USE_DM_GETOPT: $USE_DM_GETOPT
 CFLAGS:        $CFLAGS
 GLIB:          $ac_glib_libs
@@ -25172,6 +25225,7 @@ PGSQL:         $PGSQLLIB
 SQLITE:        $SQLITELIB
 SIEVE:         $SIEVEINC$SIEVELIB
 LDAP:          $LDAPINC$LDAPLIB
+MANPAGES:      $enable_manpages
 SHARED:        $enable_shared
 STATIC:        $enable_static
 CHECK:         $with_check
@@ -25181,6 +25235,7 @@ echo "${ECHO_T}
 DM_LOGDIR:     $DM_LOGDIR
 DM_CONFDIR:    $DM_CONFDIR
 DM_STATEDIR:   $DM_STATEDIR
+DM_PKGLIBDIR:  $DM_PKGLIBDIR
 USE_DM_GETOPT: $USE_DM_GETOPT
 CFLAGS:        $CFLAGS
 GLIB:          $ac_glib_libs
@@ -25190,6 +25245,7 @@ PGSQL:         $PGSQLLIB
 SQLITE:        $SQLITELIB
 SIEVE:         $SIEVEINC$SIEVELIB
 LDAP:          $LDAPINC$LDAPLIB
+MANPAGES:      $enable_manpages
 SHARED:        $enable_shared
 STATIC:        $enable_static
 CHECK:         $with_check
