merging git tree
git-svn-id: https://svn.ic-s.nl/svn/dbmail/branches/dbmail_2_2_branch@2466 7b491191-dbf0-0310-aff6-d879d4d69008

diff --git a/debian/dbmail.init b/debian/dbmail.init
--- a/debian/dbmail.init
+++ b/debian/dbmail.init
@@ -72,14 +72,20 @@ service_stop() {
 	start-stop-daemon --stop --retry 10 \
 		--pidfile ${PID_DIR}/${_name}.pid >/dev/null 2>&1 || true
 
-	pids=`pidof ${_name}`
-	if [ -n  "$pids" ]; then
-		log_failure_msg "failed"
-		return 1
-	fi
-	
-	return 0
-	
+	pidof ${_name} >/dev/null 2>&1 || return 0
+	# try harder
+	echo -n "."
+	killall ${_name} >/dev/null 2>&1 || true
+	sleep 4
+	pidof ${_name} >/dev/null 2>&1 || return 0
+	echo -n "."
+	killall -9 ${_name} >/dev/null 2>&1 || true
+	sleep 2
+	pidof ${_name} >/dev/null 2>&1 || return 0
+	echo -n "."
+	log_failure_msg "failed"
+	return 1
+
 }
 	
 service_reload() {
